using AutoQuestConflictPatcher.Configuration;
using AutoQuestConflictPatcher.Merging;
using AutoQuestConflictPatcher.Reporting;

using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace AutoQuestConflictPatcher;

public static class Program
{
    private static Lazy<AutoQuestConflictPatcherSettings>? _settings;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetTypicalOpen(GameRelease.SkyrimSE, ModKey.FromNameAndExtension("AutoQuestConflictPatcher.esp"))
            .Run(args);
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var settings = _settings?.Value ?? new AutoQuestConflictPatcherSettings();
        var report = new MergeReport();
        var scanner = new QuestConflictScanner();
        var merger = new QuestMergeEngine(report);

        foreach (var conflict in scanner.Scan(state, settings, report))
        {
            var merged = merger.Merge(conflict);
            if (merged.Equals(conflict.WinningQuest))
            {
                report.Log($"No patch needed for {conflict.DisplayName}.");
                continue;
            }

            state.PatchMod.Quests.Add(merged);
            report.Log($"Patched {conflict.DisplayName}.");
        }

        if (settings.EmitReport)
        {
            var reportPath = Path.Combine(Environment.CurrentDirectory, "AutoQuestConflictPatcher-report.txt");
            report.WriteTo(reportPath);
        }
    }
}
